server:
  port: 8080
  host: localhost

database:
  host: 172.26.37.69
  port: 3306
  user: taskuser
  password: taskpass
  name: taskapp
  charset: utf8mb4

jwt:
  secret: "taskapp-secret-key-change-in-production"
  expiration: 24h

cors:
  allowed_origins:
    - "http://localhost:*"
    - "http://127.0.0.1:*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - "*"